info:
  application: "Library Service (Unsecured)"

management:
  endpoints:
    enabled-by-default: true
    jmx:
      enabled: true
      expose: '*'
    web:
      enabled: true
      expose: '*'
  endpoint:
    health:
      show-details: true
