version: 2

jobs:
  jdk8-library-service:
    working_directory: ~/jdk8-library-service
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-service && ./gradlew build
      - store_test_results:
          path: library-service/build/test-results

  jdk8-library-enrichment:
    working_directory: ~/jdk8-library-enrichment
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-enrichment && ./gradlew build
      - store_test_results:
          path: library-enrichment/build/test-results

  jdk8-library-integration-slack:
    working_directory: ~/jdk8-library-integration-slack
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-integration-slack && ./gradlew build
      - store_test_results:
          path: library-integration-slack/build/test-results

workflows:
  version: 2
  jdk8:
    jobs:
    - jdk8-library-service
    - jdk8-library-enrichment
    - jdk8-library-integration-slack
