version: 2
jobs:
  build:
    working_directory: ~/library-service-jdk8
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run: cd library-service && ./gradlew build
      - run: cd library-enrichment && ./gradlew build
      - run: cd library-integration-slack && ./gradlew build
