info:
  application: "Library Enrichment"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{correlationId}]){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: info
    library.enrichment: debug
    utils.feign: debug

spring:
  main:
    banner-mode: "off"

management:
  endpoints:
    enabled-by-default: false
    jmx:
      enabled: false
    web:
      expose: '*'
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
      show-details: true
    conditions:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    scheduledtasks:
      enabled: true
    trace:
      enabled: true
    mappings:
      enabled: true

library:
  url: "http://localhost:8080"
  logLevel: "FULL"
  username: "curator"
  password: "curator"

datasources:
  openlibrary:
    url: "https://openlibrary.org"
    logLevel: "FULL"
